### ISSUE TITLE
Improve darc interface

### ISSUE THREAD

**Issue by kc1212** [dedis/student_18_omniledger#33]
While attempting to add online verification, I realised that the current darc interface is not straightforward to use, not modular and has some repeated code/logic. For example, when checking the request, we do not re-use the existing `Verify` or `VerifyWithCB` function. Further, it is difficult to traverse the darc because they do not have references to the delegated darcs. We need an easy way to traverse the darc because the requester/client may not know the latest darc ID (but we assume it knows the base darc ID).

We propose a few interfaces which, together, has the ability to efficient traverse the evolutions and delegations in the darcs.

```
type DB interface {
    Select(string) *Element
    Insert(string, *Element) error
}

type Element interface {
    Inner() *Darc
    Next() *Element
    Previous() *Element
    // Delegations returns a list of elements (darcs) that we delegated a certain action to.
    // The returned value must not be on the current chain.
    Delegations(action Action) []*Element
}
```

A simple DB implementation would simply store the darcs in a hash map. Where the keys are the darc IDs. A simple Element implementation would be a wrapper around an existing Darc with private fields such as `prev string` and `next string` to act as references to other darcs. The `Delegations` method must also be implemented because it involves searching the database for darcs identified by keys. The easiest way is to store a DB reference in the `Element` implementation and query the database directly.

Using the above interface, we can easily traverse the darc-tree. In a request (if it's not evolving), the client only needs to provide the action and the base ID. The server that holds the darc will be able to traverse the darc-tree and find the latest darcs, and then evaluate the expression on all of them. If one expression evaluates to true, then the request is accepted. If the request is evolving, the client sends a special request message but we run the same code as before to check whether the request is valid, the only additional step is to perform the actual evolution.

**Comment by kc1212** [comment]
In hindsight, maybe only the `DB` interface is needed. The `Element` interface can be simply a part of the `Darc struct`. The `Darc struct` would simply hold a reference to the DB and implement `Next`, `Previous` and `Delegations` using it.

**Comment by ineiti** [comment]
I don't see exactly where `DB` would fit into. The darcs will most often be held in omniledger where the latest version of the darc is stored under the _key_ of the darc-id. So we don't need being able to have `Next` and `Previous`, as we suppose that a stored darc is valid by trusting the consensus and its verification. So omniledger only needs _version - 1_ when evolving a darc, but never earlier versions.

Regarding the signature, we need to define it as a signature fulfilling an action of a darc, then we need to sign the following message:
(darci-id of action | action | parameters of action | path to signer)
- darc-id of action: is the base-darc-id where the action we want to evoke is stored
- action: the actual action, which might be one of _evolve_, _ocs-write_, _ocs-read_, ...
- parameters of action: for _evolve_ this could be the darc-id that we want to evolve
- path to signer(s): in the simplest case the action points to a public key that can verify the signature, else it can be a list of paths from the action to the actual public key

Here I also differentiate between `darc-id`, which is the hash of the current version of the darc, and `base-darc-id`, which is the `darc-id` of the darc with version == 0.

**Comment by kc1212** [comment]
If omniledger stores only the latest darc, how does he find a darc that's not the latest? For example, darc A delegates action "write" to darc B, then darc B evolves to darc C. Then, if the client makes a request for action "write" and specifies darc A, with a signature that is valid in darc C. The server has to traverse the path of evolution as well as the path of delegation to find the latest darcs, which is A or C. The client might now know the latest state of the darcs. I think traversing the evolution/delegation path is necessary for verifying requests which is why I proposed the API above.

**Comment by kc1212** [comment]
The new proposal is the following:

Client send requests to ask for permission on the service to perform an action, e.g. reading data. This request is not used for evolving a darc. The signatures in the requests should be on the following fields:

- base darc ID for where the action is stored
- action
- action message
- list of signer darcs

Every request will have multiple signatures, one from every signer darc. Every signature also has a public key attached, to identify the node that signed it. 

In the case of an evolution, the client is responsible for creating the correct darc. Hence, if multiple signatures are required. the client is responsible for collecting those signatures. Then, it will send a special request called an Evolution Request, which, in essence, just contains the new darc. The server checks that the new darc has a correct evolution and adds it to the database.

**Comment by kc1212** [comment]
A lot of changes went into the darcs since this issue was opened. We feel much more confident about the darc interface now so I'm closing this issue.
